name: Multi-run Risk Report

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'   # 06:00 Kyiv
    - cron: '0 9 * * *'   # 12:00 Kyiv
    - cron: '0 15 * * *'  # 18:00 Kyiv
    - cron: '0 17 * * *'  # 20:00 Kyiv
    - cron: '0 21 * * *'  # 00:00 Kyiv
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas folium beautifulsoup4 requests feedparser \
                      xgboost scikit-learn joblib

      - name: Analyze signals
        run: python analyze_signals.py

      - name: Generate report
        run: python generate_report.py

      - name: Build map
        run: python make_map.py

      - name: Engineer features
        run: python engineer_features.py

      - name: Train attack predictor
        run: python train_model.py

      - name: Predict attacks
        run: python predict_attacks.py

      - name: Deploy to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git checkout -B gh-pages
          git add daily_risk_report.html attack_map.html predictions_*.html
          git commit -m "Auto-update reports and predictions" || echo "No changes"
          git push -f origin gh-pages
